### ISSUE TITLE
Have problems with connecting the sql database

### ISSUE THREAD

**Issue by alslonik** [noefp/easy_gdb#1]
Hi, 
I installed the easy_gdb and it is running well on my server incl blast and all other tools, but still haven't managed to connect the sql database to it. Postgresql is installed and the perl scripts importing the annotation worked but i do not see the result on the web, and I also do not understand where annot1 is stored actually! Need some help with it, thanks!!

**Comment by noefp** [comment]
Hello,
I will try to answer your questions but I might need more details in some cases.
1. To connect to the database, there is a database_access.php file in the folder egdb_conf/ There, you have to provide the host (host=DB if you are using the Docker installation or host=localhost if not), the name of the database you created (dbname=annot1), user name (user=web_usr) y el password that you defined for the user web_usr (password=yourpwd).
2. If you followed the tutorial and the database is installed and the importing scripts worked, you could use the search for example to find the genes you imported. If you use the sample data, you could search for "gene" and you should find some results. If you completed the whole tutorial you will know the sql database worked if you can see the gene page (localhost:8000/easy_gdb/gene.php?name=gene1.1) following a link from the search output, BLAST output or clicking on a gene in the genome browser.
3. annot1 is stored in indexed files of the Postgres database, you usually do not access these files directly but throught the sql console or using the importing scripts. It is in the postgres-data folder if you used the Docker installation or in your system files (controlled by Postgres) if you did not use Docker.

I hope it helped. If you still have more questions or do not get the database working let me know if you used Docker or not and what do you see when you try the solutions I mentioned.

If you want you can write me to my email (in the easyGDB publication) to send me screenshots and to figure out how to solve this issue. Later we can add the solution here.

**Comment by alslonik** [comment]
Hi, and thank you so much for your answer! I missed it somehow. 

1. I did manage at the end to access the database that I created and imported my data to it, with the help of the perl scripts in the easy_gdb/scripts folder. It works! Thank you! 
2. Now, I am trying to change the headers of the table presented on the page, for example, and I do not find which file should I edit?  In the original setting it is "Gene, Term, Description". In my case, I need the field "Orthogroup". Could you please direct to the file, where I modify the table structure ?
3. Also, is it possible to create a database of slightly different schema and let it be visible on the page? I mean - instead of importing the gene list and annotations separately. I have an annotation  table on postgres and I want to connect to it and be able to see it on  the page? I am really a newbie in both postgres and php, so I need your help with this... 
4. I did not use Docker. 

Many many thanks so far! 
Alex

**Comment by noefp** [comment]
Hi Alex,
1. I am happy that worked.
2. It is not possible to edit the current schema provided with easyGDB, but I could include a module to handle orthogroups.
3. It would be possible to add your credentials to your custom database in the database_access.php file creating a new function similar to getConnectionString(), and then create some custom pages that would use that database. You could try to reuse some of the code of easyGDB to create your SQL queries and to display the data.

You could wirte me an email (https://www.ihsm.uma-csic.es/investigadores/1031) with your custom schema and which type of modules you will like to include in your genomic portal (such as orthgroups), and I could try to implement solutions in easyGDB that fit to those needs if they might be useful for other users.

I will close the issue since you already solved the database connection issue. We can open a new one for the implementation of custom schemas or other topics

Best regards,
Noe
